language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - bin/phpunit --coverage-text --debug

notifications:
  email:
    recipients:
      - si-integration@smartandco.com
    on_success: change
    on_failure: always
